# Generated by Django 4.2.6 on 2023-10-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(upload_to="product_images/"),
        ),
    ]
