# Generated by Django 4.2.6 on 2023-10-31 20:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0002_alter_product_img"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="img_width",
        ),
    ]
