# Generated by Django 4.2.6 on 2023-11-06 11:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0004_order_orderitem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrderItem",
            new_name="OrderItems",
        ),
    ]
