# Generated by Django 4.2.6 on 2023-11-06 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0005_rename_orderitem_orderitems"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
