# Generated by Django 4.2.6 on 2023-11-11 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("back", "0011_alter_product_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="img",
            field=models.ImageField(upload_to=""),
        ),
    ]
